parameters:
#    mesd_console_generator.example.class: MESD\Console\GeneratorBundle\Example

services:
#    mesd_console_generator.example:
#        class: %mesd_console_generator.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
